version: '3.8'

services:
  talkbridge:
    build: .
    container_name: talkbridge-app
    ports:
      - "8501:8501"
    volumes:
      # Data persistence
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src/demo/samples:/app/src/demo/samples
      # Configuration (optional)
      - ./src/config.py:/app/src/config.py:ro
    environment:
      # System settings
      - DEMO_MODE=true
      - DEBUG=false
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      
      # Audio settings
      - SAMPLE_RATE=22050
      - AUDIO_CHANNELS=1
      - CHUNK_DURATION=5.0
      
      # UI settings
      - UI_HOST=0.0.0.0
      - UI_PORT=8501
      - AUTH_ENABLED=true
      - SESSION_TIMEOUT=3600
      
      # Performance settings
      - MAX_WORKERS=4
      - CHUNK_SIZE=1024
      - BUFFER_SIZE=4096
      
      # Timeout settings
      - REQUEST_TIMEOUT=30.0
      - AUDIO_TIMEOUT=10.0
      - MODEL_TIMEOUT=60.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8501/_stcore/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - talkbridge-network

  # Optional: Redis for session storage (if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: talkbridge-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - talkbridge-network

networks:
  talkbridge-network:
    driver: bridge

volumes:
  # redis_data:  # Uncomment if using Redis

# Usage:
# docker-compose up -d
# docker-compose down
# docker-compose logs -f talkbridge
# docker-compose exec talkbridge bash

# Environment-specific configurations:

# Development mode:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

# Production mode:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

# Demo mode (default):
# docker-compose up -d

# Live mode (requires hardware):
# docker-compose -f docker-compose.yml -e DEMO_MODE=false up -d 