# TalkBridge Desktop Conda Environment - OPTIMIZED FOR DESKTOP
# ============================================================
# 
# Conda environment specifically for TalkBridge Desktop application
# Python 3.11 for maximum compatibility with TTS, mediapipe, and ML packages
# Excludes web frameworks (Flask, Streamlit) - Desktop only
#
# Environment creation:
# conda env create -f environment-desktop.yaml
#
# Activation:
# conda activate talkbridge-desktop-env
#
# Post-installation verification:
# python -c "import sys; print(f'Python {sys.version}')"
# python -c "import customtkinter, torch, librosa, mediapipe; print('All dependencies OK!')"

name: talkbridge-desktop-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip

  # Core scientific stack
  - numpy
  - scipy
  - matplotlib

  # Audio / Media
  - ffmpeg
  - libsndfile
  - pydub

  # GUI / Desktop (conda only for what exists)
  - pyside6
  - pyqt

  # PyTorch CPU only (no ROCm on Windows)
  - pytorch
  - torchaudio
  - cpuonly

  # Utilities
  - python-dotenv
  - rich
  - colorlog
  - click
  - tqdm
  - typeguard
  - pydantic>=2

  # Dev / Testing
  - pytest
  - pytest-qt
  - pytest-cov
  - black
  - git

  - pip:
      # GUI package (pip only)
      - customtkinter

      # HuggingFace / Speech
      - "transformers>=4.39"
      - tokenizers==0.15.*
      - sentencepiece
      - TTS==0.22.*
      - webrtcvad

      # Translation
      - deep-translator
      - argostranslate

      # Vision / Audio
      - opencv-python>=4.10
      - mediapipe>=0.10
      - pillow>=10.3
      - pygame>=2.6